Repository asdf2014/druid-helm, pull requests merged in 2024-07, with the labels that each got.

#55 Update index for 29.1.9 release
  index.yaml
Labels: release

#56 Upgrade Druid from 29.0.1 to 30.0.0
  Chart.yaml
  README.md
  index.yaml
  releases/druid-30.0.0.tgz
Labels: dependency

#57 Release 30.0.0
  README.md
  index.yaml
  releases/druid-30.0.0.tgz
Labels: release

#58 Update helm chart port forwarding commands
  templates/NOTES.txt
Labels: documentation

#59 Release 30.0.1
  Chart.yaml
  README.md
  index.yaml
  releases/druid-30.0.1.tgz
Labels: release

#60 Upgrade Druid Docker image from 29.0.1 to 30.0.0
  Chart.yaml
  README.md
  index.yaml
  releases/druid-30.0.1.tgz
  values.yaml
Labels: release

#61 Upgrade ZooKeeper Helm Chart from 13.4.3 to 13.4.10
  Chart.lock
  Chart.yaml
  README.md
  charts/zookeeper-13.4.10.tgz
  charts/zookeeper-13.4.3.tgz
  index.yaml
  releases/druid-30.0.3.tgz
Labels: dependency
