Repository asdf2014/druid-helm, pull requests merged in 2024-05, with the labels that each got.

#44 Upgrade PostgreSQL Helm Chart from 15.2.5 to 15.2.8
  Chart.lock
  Chart.yaml
  charts/postgresql-15.2.5.tgz
  charts/postgresql-15.2.8.tgz
  index.yaml
  releases/druid-29.1.4.tgz
Labels: dependency

#45 Upgrade PostgreSQL Helm Chart from 15.2.5 to 15.2.8
  Chart.lock
  Chart.yaml
  README.md
  charts/postgresql-15.2.5.tgz
  charts/postgresql-15.2.8.tgz
  index.yaml
  releases/druid-29.1.5.tgz
Labels: dependency

#46 Correct default value in README.md
  README.txt
Labels: documentation

#47 Revert the renaming of README file in #46
  README.md
Labels: documentation

#48 Release 29.1.6
  Chart.yaml
  README.md
  index.yaml
  releases/druid-29.1.6.tgz
Labels: release

#51 Release 29.1.7
  Chart.yaml
  README.md
  index.yaml
  releases/druid-29.1.7.tgz
Labels: release
